# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tellme < Formula
  desc "A blazing fast local CLI assistant to verify installed tools and versions."
  homepage "https://github.com/eaccmk/tellme"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eaccmk/tellme/releases/download/v1.5.0/tellme_1.5.0_darwin_amd64.tar.gz"
      sha256 "099477a8b8ca0c76bac3e6fc8b0e04d67b76cea055657f855dd081a2afe6c541"

      define_method(:install) do
        bin.install "tellme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eaccmk/tellme/releases/download/v1.5.0/tellme_1.5.0_darwin_arm64.tar.gz"
      sha256 "3738c62ecb5ad20bbcdd73898de27b15b38bcbeb7980fd0a4ae44e255559e7e5"

      define_method(:install) do
        bin.install "tellme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eaccmk/tellme/releases/download/v1.5.0/tellme_1.5.0_linux_amd64.tar.gz"
      sha256 "f8d7a0f5f5ed15a74014501c4dbea7e816e66806754fddc231e21c28c31cc020"
      define_method(:install) do
        bin.install "tellme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eaccmk/tellme/releases/download/v1.5.0/tellme_1.5.0_linux_arm64.tar.gz"
      sha256 "507a73e29006931177522807d4ad9394d4eebf8839fc2febd90760135985014c"
      define_method(:install) do
        bin.install "tellme"
      end
    end
  end

  def caveats
    <<~EOS
      To prevent shell wildcard/globbing errors (e.g. when typing question marks like 'tellme do I have python?'), configure your shell profile:

        echo 'eval "$(tellme init)"' >> ~/.zshrc
    EOS
  end
end
