# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tellme < Formula
  desc "A blazing fast local CLI assistant to verify installed tools and versions."
  homepage "https://github.com/eaccmk/tellme"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eaccmk/tellme/releases/download/v1.2.0/tellme_1.2.0_darwin_amd64.tar.gz"
      sha256 "73f1891173cdb5b20a17151a3212aa80404079626029b0429752f902baf2d95d"

      define_method(:install) do
        bin.install "tellme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eaccmk/tellme/releases/download/v1.2.0/tellme_1.2.0_darwin_arm64.tar.gz"
      sha256 "03afc7dda0812098ad0690bad76240e5f67c29daaf4b0e2ec5727405f928f4f7"

      define_method(:install) do
        bin.install "tellme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eaccmk/tellme/releases/download/v1.2.0/tellme_1.2.0_linux_amd64.tar.gz"
      sha256 "2eedf6acf28b2ac2e3d400c1e518ffb562d30572966de7c5585d9955f745d68b"
      define_method(:install) do
        bin.install "tellme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eaccmk/tellme/releases/download/v1.2.0/tellme_1.2.0_linux_arm64.tar.gz"
      sha256 "118971b6b1fce26e6431684589298a76aec4a602c39b16c1dac7f1d1fcd49c58"
      define_method(:install) do
        bin.install "tellme"
      end
    end
  end

  def caveats
    <<~EOS
      To prevent shell wildcard/globbing errors (e.g. when typing question marks like 'tellme do I have python?'), add the following to your shell profile (~/.zshrc for Zsh):

        eval "$(tellme init)"
    EOS
  end
end
